variables:
  host: dhsaz-apim-api-dev.azure-api.net

jobs:
- job: jmeter
  pool:
    name: Default
    demands:
    - 'Agent.Name -equals W10USI170354'
    vmImage: ubuntu-latest
  displayName: Run JMeter tests
  steps:
  – task: Bash@3
    inputs:
      targetType: 'inline'
      script: 'env | sort'
  - task: Bash@3
    displayName: Execute JMeter tests
    inputs:
      targetType: filePath
      filePath: 'jmeter/test.sh'
      arguments: '$PWD CartTest.jmx $(host)'
      workingDirectory: jmeter
      failOnStderr: false
  - task: PublishPipelineArtifact@1
    displayName: Publish JMeter Report
    inputs:
      targetPath: jmeter/report
      artifact: jmeter
