trigger:
- master

jobs:
- job: jmeter
  pool:
    name: Default
    demands:
    - 'Agent.Name -equals W10USI170354'
    vmImage: ubuntu-latest
  displayName: Run JMeter tests

steps:
- script: echo 'Lets run a test on Azure!' 
- task: ShellScript@2
  inputs:
    scriptPath: 'jmeter/test.sh'
    arguments: '$PWD CartTest.jmx $(host)'
    workingDirectory: jmeter
    failOnStderr: false
  displayName: 'Use Flood'
  env:
    MY_FLOOD_TOKEN: $(flood_api_token)
 
- task: PublishPipelineArtifact@1
  displayName: Publish JMeter Report
  inputs:
    scriptPath: jmeter/report
    artifact: jmeter
