trigger:
- master
pool:
    name: Default
    vmImage: ubuntu-latest
    displayName: Run JMeter tests
steps:
- script: echo 'Lets run a test on Azure!' 
- task: ShellScript@2
  inputs:
    scriptPath: 'jmeter/test.sh'
    arguments: '$PWD CartTest.jmx $(host)'
    workingDirectory: jmeter
    failOnStderr: false
  displayName: Running'
  
- task: PublishPipelineArtifact@1
  displayName: Publish JMeter Report
  inputs:
    scriptPath: jmeter/report
    artifact: jmeter
