jobs:
- job: jmeter
   pool: default
  displayName: Run JMeter tests
  steps:
  - task: Bash@3
    displayName: Execute JMeter tests
    inputs:
      targetType: filePath
      filePath: 'jmeter/test.sh'
      arguments: '$PWD CartTest.jmx $(host)'
      workingDirectory: jmeter
      failOnStderr: false
  - task: PublishPipelineArtifact@1
    displayName: Publish JMeter Report
    inputs:
      targetPath: jmeter/report
      artifact: jmeter
